-- ============================================================================
-- E-BIKE RENTAL & COURIER MANAGEMENT — CORE SCHEMA
-- ============================================================================
-- Migration 1 of 4: Core domain tables (bikes, couriers, rental plans)
--
-- This migration creates the foundational tables for the e-bike rental business.
-- Bikes are assets (not products), couriers are service users (not customers).
--
-- Business Rules Implemented:
--   - Couriers can have max 1 bike at a time (enforced by trigger)
--   - Weekly plan = 7 days from assignment (not calendar week)
--   - Early return = full charge (no prorating)
--   - Damage assessment requires manager approval
--   - Photos required for bikes and maintenance
--
-- Migration order:
--   20260821000001 - bikes, couriers, rental plans (this file)
--   20260821000002 - assignments and earnings
--   20260821000003 - maintenance and inspections
--   20260821000004 - update roles and RLS, remove old tables
-- ============================================================================

-- ============================================================================
-- NEW ENUMS
-- ============================================================================

CREATE TYPE bike_status AS ENUM (
    'available',    -- Ready to be assigned
    'assigned',     -- Currently with a courier
    'maintenance',  -- Being serviced
    'damaged',      -- Requires repair before use
    'retired'       -- Permanently out of service
);

CREATE TYPE courier_status AS ENUM (
    'active',       -- Working
    'inactive',     -- Not currently working
    'suspended'     -- Temporarily blocked
);

CREATE TYPE duration_unit AS ENUM (
    'days',
    'weeks',
    'months'
);

-- ============================================================================
-- BIKES
-- ============================================================================
-- Bikes are assets, not products. They have status, maintenance history,
-- and are tracked individually. No sale_price, no SKU, no inventory quantity.

CREATE TABLE bikes (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id   UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    bike_number       TEXT NOT NULL,              -- Internal: EB-001, EB-002
    serial_number     TEXT,                       -- Manufacturer serial
    model             TEXT NOT NULL,
    status            bike_status DEFAULT 'available',
    purchase_date     DATE,
    purchase_price    DECIMAL(15, 2),
    condition_notes   TEXT,
    battery_info      TEXT,                       -- Capacity, health, etc.
    image_url         TEXT NOT NULL,              -- REQUIRED: Storage path for bike photo
    created_by        UUID REFERENCES user_profiles(id),
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ,
    UNIQUE(organization_id, bike_number),
    CHECK (image_url IS NOT NULL AND image_url != '')  -- Photos required
);

CREATE INDEX idx_bikes_org ON bikes(organization_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_bikes_status ON bikes(organization_id, status) WHERE deleted_at IS NULL;
CREATE INDEX idx_bikes_number ON bikes(organization_id, bike_number);

COMMENT ON TABLE bikes IS
  'E-bikes owned by the company. Assets with status tracking, not products for sale.
   Photos are REQUIRED (image_url NOT NULL) for fleet management.';
COMMENT ON COLUMN bikes.bike_number IS
  'Internal identifier (EB-001). Generated by trigger, unique per organization.';
COMMENT ON COLUMN bikes.status IS
  'Current state. Only "available" bikes can be assigned to couriers.
   Enforced by assignment validation trigger.';
COMMENT ON COLUMN bikes.image_url IS
  'Path in bike-images storage bucket. REQUIRED field. Private bucket, displayed via signed URL.';

CREATE TRIGGER trg_bikes_updated_at BEFORE UPDATE ON bikes
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- COURIERS
-- ============================================================================
-- People who rent bikes to perform deliveries. Not customers (they don't buy
-- on credit). Financial model is: gross earnings - deductions = net payout.
--
-- Business rule: Max 1 bike per courier at a time (enforced by trigger).

CREATE TABLE couriers (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id       UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    courier_code          TEXT NOT NULL,
    full_name             TEXT NOT NULL,
    phone                 TEXT NOT NULL,
    identification_number TEXT,                   -- Passport/ID (sensitive)
    address               TEXT,
    emergency_contact     TEXT,
    start_date            DATE NOT NULL DEFAULT CURRENT_DATE,
    status                courier_status DEFAULT 'active',
    yandex_identifier     TEXT,                   -- For future Yandex Food integration
    notes                 TEXT,
    created_by            UUID REFERENCES user_profiles(id),
    created_at            TIMESTAMPTZ DEFAULT NOW(),
    updated_at            TIMESTAMPTZ DEFAULT NOW(),
    deleted_at            TIMESTAMPTZ,
    UNIQUE(organization_id, courier_code)
);

CREATE INDEX idx_couriers_org ON couriers(organization_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_couriers_status ON couriers(organization_id, status) WHERE deleted_at IS NULL;
CREATE INDEX idx_couriers_phone ON couriers(organization_id, phone) WHERE deleted_at IS NULL;

COMMENT ON TABLE couriers IS
  'Delivery couriers who rent bikes. Service users, not customers with credit accounts.
   Business rule: Max 1 bike per courier at a time (enforced in assignment trigger).';
COMMENT ON COLUMN couriers.courier_code IS
  'Internal identifier (COU-0001). Generated by trigger, unique per organization.';
COMMENT ON COLUMN couriers.identification_number IS
  'Passport or ID number. Sensitive PII - handle with care, encrypt at rest.';
COMMENT ON COLUMN couriers.yandex_identifier IS
  'Yandex Food courier ID for future API integration. NULL in MVP (manual entry).';

CREATE TRIGGER trg_couriers_updated_at BEFORE UPDATE ON couriers
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- RENTAL PLANS
-- ============================================================================
-- Configurable pricing plans. Company creates its own plans (daily, weekly,
-- monthly). Plans are applied to assignments, and the assignment snapshots
-- the plan so price changes don't retroactively rewrite history.
--
-- Business rule: Early return = full charge (no prorating).

CREATE TABLE rental_plans (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    organization_id   UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name              TEXT NOT NULL,               -- "Weekly Plan", "Monthly Plan"
    duration_value    INTEGER NOT NULL CHECK (duration_value > 0),
    duration_unit     duration_unit NOT NULL,
    price             DECIMAL(15, 2) NOT NULL CHECK (price >= 0),
    description       TEXT,
    is_active         BOOLEAN DEFAULT TRUE,
    created_by        UUID REFERENCES user_profiles(id),
    created_at        TIMESTAMPTZ DEFAULT NOW(),
    updated_at        TIMESTAMPTZ DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ,
    UNIQUE(organization_id, name)
);

CREATE INDEX idx_rental_plans_org ON rental_plans(organization_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_rental_plans_active ON rental_plans(organization_id, is_active)
    WHERE deleted_at IS NULL AND is_active = TRUE;

COMMENT ON TABLE rental_plans IS
  'Rental pricing plans (daily, weekly, monthly). Company-configurable.
   Business rule: Full charge applies even for early returns (no prorating).';
COMMENT ON COLUMN rental_plans.duration_value IS
  'Number of duration_units. Example: 7 days, 4 weeks, 1 month.
   Weekly = 7 days from assignment date, not calendar week.';
COMMENT ON COLUMN rental_plans.price IS
  'Rental cost. Applied as deduction in earnings period. Full charge for partial periods.';

CREATE TRIGGER trg_rental_plans_updated_at BEFORE UPDATE ON rental_plans
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- AUTO-NUMBERING FUNCTIONS
-- ============================================================================
-- Generate sequential codes for bikes and couriers, following the house style
-- established for customers (CUST-0001) and invoices (INV-2026-0001).

CREATE OR REPLACE FUNCTION generate_bike_number(org_id UUID)
RETURNS TEXT AS $$
DECLARE
  next_num INTEGER;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(bike_number FROM '[0-9]+$') AS INTEGER)), 0) + 1
  INTO next_num
  FROM bikes
  WHERE organization_id = org_id
    AND bike_number ~ '^EB-[0-9]+$';

  RETURN 'EB-' || LPAD(next_num::TEXT, 3, '0');
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION generate_bike_number IS
  'Generates next bike number: EB-001, EB-002, etc. Scoped to organization.';

CREATE OR REPLACE FUNCTION generate_courier_code(org_id UUID)
RETURNS TEXT AS $$
DECLARE
  next_num INTEGER;
BEGIN
  SELECT COALESCE(MAX(CAST(SUBSTRING(courier_code FROM '[0-9]+$') AS INTEGER)), 0) + 1
  INTO next_num
  FROM couriers
  WHERE organization_id = org_id
    AND courier_code ~ '^COU-[0-9]+$';

  RETURN 'COU-' || LPAD(next_num::TEXT, 4, '0');
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION generate_courier_code IS
  'Generates next courier code: COU-0001, COU-0002, etc. Scoped to organization.';

-- ============================================================================
-- AUTO-NUMBERING TRIGGERS
-- ============================================================================
-- Assign codes on INSERT if not provided by the application.

CREATE OR REPLACE FUNCTION fn_assign_bike_number()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.bike_number IS NULL OR NEW.bike_number = '' THEN
    NEW.bike_number := generate_bike_number(NEW.organization_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_assign_bike_number
BEFORE INSERT ON bikes
FOR EACH ROW
EXECUTE FUNCTION fn_assign_bike_number();

CREATE OR REPLACE FUNCTION fn_assign_courier_code()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.courier_code IS NULL OR NEW.courier_code = '' THEN
    NEW.courier_code := generate_courier_code(NEW.organization_id);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_assign_courier_code
BEFORE INSERT ON couriers
FOR EACH ROW
EXECUTE FUNCTION fn_assign_courier_code();

COMMENT ON FUNCTION fn_assign_bike_number IS
  'Assigns bike_number on INSERT if not provided. Prevents NULL or empty string.';
COMMENT ON FUNCTION fn_assign_courier_code IS
  'Assigns courier_code on INSERT if not provided. Prevents NULL or empty string.';

-- ============================================================================
-- STORAGE BUCKETS FOR BIKE IMAGES
-- ============================================================================
-- Private bucket. Bike photos are commercially sensitive (shows fleet size,
-- condition). Display via signed URLs, not public URLs.
--
-- Photos are REQUIRED per business rules.
-- RLS policies will be added in migration 20260821000004 after role updates.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'bike-images',
  'bike-images',
  FALSE,
  5242880,  -- 5 MB
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

COMMENT ON TABLE bikes IS
  'E-bikes owned by the company. Assets with status tracking and maintenance history.
   Not products for sale - there is no sale_price, no inventory quantity.
   Each bike is tracked individually from purchase through retirement.
   Photos REQUIRED (business rule) for fleet management.';
